server:
  port: 8906
  servlet:
    context-path: /triangulum

  ####Jetty specific properties########
  jetty:
    max-http-post-size: 0

spring:
  jackson:
    default-property-inclusion: NON_NULL

upload:
  path: /proj
  categoryList:
    - weather
    - pet