spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    context-path: /triangulum
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      springframework: INFO