server:
  port: 0
  servlet:
    context-path: /triangulum

spring:
  jackson:
    default-property-inclusion: NON_NULL

upload:
  path: /Users/chengweiou/Desktop/project/universe/triangulum
  categoryList:
    - weather
    - pet